from disarm_gears.gears.gpy_plugins.gpy_regression import GPyRegression
from disarm_gears.gears.gpy_plugins.gpy_classification import GPyClassification
from disarm_gears.gears.gpy_plugins.gpy_regression_proportions import GPyRegressionProportions
